version: '3.8'

services:
  app:
    build: .
    ports:
      - "3003:3003"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 3003
    command: python src/app.py
